### ISSUE TITLE
Provide a latest_handshake_delay (or similar value)

### ISSUE THREAD

**Issue by mmahacek** [MindFlavor/prometheus_wireguard_exporter#100]
Add an additional metric that is essentially `now - timestamp` of the latest heartbeat. This makes it easier for me to persist a value of how long it's been since the last handshake.

**Comment by MindFlavor** [comment]
Working on it: [branch issue/100](https://github.com/MindFlavor/prometheus_wireguard_exporter/tree/issue/100).
