### ISSUE TITLE
How to pass `PROMETHEUS_WIREGUARD_EXPORTER_CONFIG_FILE_NAMES` via docker

### ISSUE THREAD

**Issue by kramrm** [MindFlavor/prometheus_wireguard_exporter#113]
Since Docker runs in a separate environment, I can't reference the wg0.conf file from the host system, and if I map the file as a pass through volume mount, I get a permission issue accessing the config file.  How would I pass this in so I can get friendly names while running as a container?

**Comment by Jodu555** [comment]
Had the same issue!
I used the following docker command to map the dir /etc/wireguard to /wireguard before I gave it Recursive 777 rights! 

```bash
chmod -R 7777 /etc/wireguard/
```
> To give the dir all permissions

```bash
docker run -d --net=host --cap-add=NET_ADMIN --name wgexporter --restart unless-stopped -v /etc/wireguard:/wireguard:ro mindflavor/prometheus-wireguard-exporter -a true -n /wireguard/wg0.conf` 
```
> Then to start the image!!

Worked for me!
