### ISSUE TITLE
friendly_name: What do I need to do to get it to work?

### ISSUE THREAD

**Issue by n0valis** [MindFlavor/prometheus_wireguard_exporter#125]
I have added friendly_name and friendly_json to my wireguard .conf file as yu suggested.
But they dont show up in the metrics. Is there anything else that I have missed?
At some time you mention "enable the flag ". Which one? Where?
Thanks for your patience.

**Comment by greigm** [comment]
The documentation is a little confusing here, but does make sense if you read further. The flag is -n and it takes the path to your wireguard config file which holds your peer definitions. Eg. -n /etc/wireguard/wg0.conf. Note that if you are running in docker, you will need to map this as a volume or it will not be readable. Hope this helps - it took me longer than it should have to work it out also! 😁

**Comment by n0valis** [comment]
You made my day. Thanks man!

**Comment by greigm** [comment]
You're most welcome. Glad I could help.
