### ISSUE TITLE
received and sent bytes appear to be swapped

### ISSUE THREAD

**Issue by traxo-xx** [MindFlavor/prometheus_wireguard_exporter#13]
Hi!
I noticed, that the values for `wireguard_sent_bytes_total` and `wireguard_received_bytes_total` appear to be swapped. For example the exporter shows the following output for a specific peer:
> wireguard_sent_bytes_total{interface="wg1",public_key="XXXX",allowed_ips="10.200.100.5/32"} 32777256
> wireguard_received_bytes_total{interface="wg1",public_key="XXXX",allowed_ips="10.200.100.5/32"} 937571768

This doesn't match the output of `wg show wg1 dump` for this peer: 
```transfer: 31.07 MiB received, 888.92 MiB sent```
A `wg show wg1 dump` looks like this for the peer:
```XXXX    XXXX    1.2.3.4:26061    10.200.100.5/32 1569256565      32610008        932829020       off```

 According to the [man page](https://git.zx2c4.com/WireGuard/about/src/tools/man/wg.8) for `wg` the order here is
> public-key, preshared-key, endpoint, allowed-ips, latest-handshake, transfer-rx, transfer-tx, persistent-keepalive

Are the values in the exporter's output actually swapped or am I just misunderstanding the wording?

**Comment by MindFlavor** [comment]
I think you are right, the output is swapped :man_facepalming: !

Or, rather, I'm parsing the order wrong. I'll fix it ASAP!

**Comment by traxo-xx** [comment]
Works as expected now. Thank you for the quick fix!
