### ISSUE TITLE
AllowedIps entry not found in lines

### ISSUE THREAD

**Issue by markthehipster** [MindFlavor/prometheus_wireguard_exporter#28]
Hey MindFlavor, 

I just encountered an issue where I get this on the metrics page if `-n` is set to one of our configs. 

`[2020-04-28T16:05:13Z WARN  prometheus_exporter_base] internal server error == AllowedIPsEntryNotFound { lines: ["PublicKey = <redacted> =", "AllowedIps = 192.168.1.1/32", "PersistentKeepalive = 25", "# Dudes-phone"] }`

It seems like that the app is trying to look for `AllowedIPs` and doesn't like `AllowedIps`
Is there anything I clould do with this one to fix it? 
Also, is it possible to specify multiple configs? We have multiple interfaces with multiple configs,but the `-n` flag is making our `wg1.conf` file the main conf file, even though we have more than 5-10. 

Thank you! 
Mark

**Comment by MindFlavor** [comment]
Yes, right now the parsing is case sensitive. 
The relevant code is here: [https://github.com/MindFlavor/prometheus_wireguard_exporter/blob/2013f8b5af761458fe69e0f363e8febe7cdd632a/src/wireguard_config.rs#L36-L44](https://github.com/MindFlavor/prometheus_wireguard_exporter/blob/2013f8b5af761458fe69e0f363e8febe7cdd632a/src/wireguard_config.rs#L36-L44).

I might render it case insensitive by converting it to lowercase first. I will add the code in a separate issue. 

As for the multiple configs, it is not possible for now. I will add the issue but for the time being you can circumvent the problem by spawning multiple instances.

**Comment by MindFlavor** [comment]
Support for multiple interfaces from the command line is implemented in release [3.3.1](https://github.com/MindFlavor/prometheus_wireguard_exporter/releases/tag/3.3.1) via PR [https://github.com/MindFlavor/prometheus_wireguard_exporter/pull/31](https://github.com/MindFlavor/prometheus_wireguard_exporter/pull/31).

**Comment by MindFlavor** [comment]
Support for case insensitive parsing is implemented in release [https://github.com/MindFlavor/prometheus_wireguard_exporter/releases/tag/3.3.2](https://github.com/MindFlavor/prometheus_wireguard_exporter/releases/tag/3.3.2) via PR #32. 

Please let me know if it solves your problem!
