### ISSUE TITLE
provide docker image

### ISSUE THREAD

**Issue by poblin-orange** [MindFlavor/prometheus_wireguard_exporter#36]
Your exporter is very interesting.
However, rust runtime is not easy to set up. An image, maybe based on official https://hub.docker.com/_/rust would be valuable. Would extend possible usage on docker and k8s

**Comment by MindFlavor** [comment]
It's an excellent idea. We will need to make sure the container could spawn `wg show <interface> dump` on the host (or even another container). Maybe prebuilt binaries can help here as well.

**Comment by poblin-orange** [comment]
Sure. Rust on Dockerfile might be complex to set up, but once done, its easy to pushlish the image on dockerhub from github.

Maybe the kilo project could be used as inspiration with wg binary integration .
https://github.com/squat/kilo

They consider wireguard must be preinstalled on host vms, and i guess they allow priviliged access to the host binary.

**Comment by poblin-orange** [comment]
travis seem to have native support for rust travis build. https://docs.travis-ci.com/user/languages/rust/

**Comment by qdm12** [comment]
See #39. We just need to setup a CI pipeline (I'm familiar with it using Github actions) to build and push the Docker image to a Docker Hub account.

**Comment by poblin-orange** [comment]
@qdm12 @MindFlavor i guess we can close this. One (probly stupid) question: is the resulting image built and uploaded to dockerhub ? I cant find it :-(

**Comment by qdm12** [comment]
Uh no sorry for postponing this. I'll try to add the CI now to automatically push to Docker hub.

**Comment by qdm12** [comment]
Actually I just realized, my CI PR has already been merged.
Unfortunately, I made a typo to build from the master branch, so I made [another PR](https://github.com/MindFlavor/prometheus_wireguard_exporter/pull/42). That should build and push the image once it's merged.

**Comment by qdm12** [comment]
@MindFlavor can you try pushing to master (anything really, even a PR should work)  to trigger the [buildx-latest workflow](https://github.com/MindFlavor/prometheus_wireguard_exporter/actions?query=workflow%3A%22Buildx+latest%22)? Thanks!
