### ISSUE TITLE
Implement a wireguard_up key

### ISSUE THREAD

**Issue by jpds** [MindFlavor/prometheus_wireguard_exporter#37]
There should be a `wireguard_up` boolean key that shows if the WireGuard interface being monitored is enabled or not.

**Comment by MindFlavor** [comment]
AFAIK the `wg show dump` does not report disabled interfaces. This should reflect in the output with the missing information. I would use the [`absent` Prometheus function](https://prometheus.io/docs/prometheus/latest/querying/functions/#absent) to show this graphically.
