### ISSUE TITLE
CI to build and push Docker image

### ISSUE THREAD

**Issue by qdm12** [MindFlavor/prometheus_wireguard_exporter#40]
Add a Github actions (free) CI build to build the Docker image for several cpu architectures and push it to Docker Hub.

To do so, please @MindFlavor create yourself a Docker hub account and set a Github secret (in the repo settings) `DOCKER_PASSWORD` with your Docker hub password. I'll take care of the CI config in a PR.

We should also add readme badges for it, because it's nice 😉

**Comment by MindFlavor** [comment]
Ok secret created! 
Thank you again!

**Comment by qdm12** [comment]
Cool, I'm working on it now. What's your Docker Hub username also?

**Comment by MindFlavor** [comment]
My usename is [mindflavor](https://hub.docker.com/u/mindflavor). The name sounds good!

**Comment by qdm12** [comment]
Hello there, sorry for the delay 😉
I just opened another [PR](https://github.com/MindFlavor/prometheus_wireguard_exporter/pull/42) to fix a copy paste typo I made regarding the build workflow from the `master` branch to build a `:latest` Docker image.
Once that's done, I'll do one final PR to have readme badges regarding the number of docker pulls etc.

Also, I probably won't do it anytime soon, but there is [rust-embedded/cross](https://github.com/rust-embedded/cross) which we could use here together with Docker's buildx to build Docker images for all CPU architectures. But that's probably going to be quite some gymnastics 😞

**Comment by MindFlavor** [comment]
Yes, cross compilation is a pain unfortunately :crying_cat_face: . At least this project does not require external dependencies to C libraries (besides rust's, that is).

**Comment by cuotos** [comment]
@qdm12 How are you updating the "Dockerfile" and "Build" contents on docker hub? I've used the Description updater before but not updated the other tabs.

**Comment by qdm12** [comment]
Actually the build and push pipeline (see in Github Actions, docker buildx latest) didn't trigger. @MindFlavor do you mind trying to push anything on the master branch to see if it triggers

**Comment by MindFlavor** [comment]
I did a simple push and it seems to be working! Great job @qdm12! 👍 (the image already has over 10k pulls which is *unexpected* to say the least 😮).

I'm closing this!
