### ISSUE TITLE
Friendly names are not matched if PublicKey contains comment

### ISSUE THREAD

**Issue by arisudesu** [MindFlavor/prometheus_wireguard_exporter#52]
As says the title, friendly names are not matched with public keys, if the public key line contains comment.

My wireguard config looks like this:
```
[Interface]
Address    = ...
ListenPort = ...
PrivateKey = ...

[Peer]
# friendly_name = mobile
PublicKey  = my-mobile-public-key  # my-private-key-in-comment
AllowedIPs = ...

[Peer]
# friendly_name = home
PublicKey  = my-home-public-key  # my-private-key-in-comment
AllowedIPs = ...
```

With this config, no friendly names are exported, although this is valid wireguard conf file.

If I modify  peer config like this:
```
[Peer]
# friendly_name = home
PublicKey  = my-home-public-key
AllowedIPs = ...
```
Then friendly names work.

**Comment by MindFlavor** [comment]
mmm this is weird and most likely a bug. 
Thank you for reporting, the repro is quite clear 👍 !

**Comment by qdm12** [comment]
> Then friendly names work.

What client are you using on that peer?

I don't know/think friendly names are part of the wireguard original program.

**Comment by MindFlavor** [comment]
Yes it was a bug indeed. This is what happens when you roll your custom parser 🤷‍♂️. 

The above PR should fix this: can you try it and get back to me please?

**Comment by arisudesu** [comment]
A quick check shows that this is now working correctly. Thanks!
