### ISSUE TITLE
Support multiple config files for friendly names/jsons

### ISSUE THREAD

**Issue by tobikris** [MindFlavor/prometheus_wireguard_exporter#61]
Thanks for the great tool!

I would like to use the nice friendly_name feature for all my interfaces. From my understanding you can only specify a single config file that is used for the friendly tag extraction though.

My idea would be to either allow multiple occurrences of the `-n` flag or allow to specify multiple files (e.g. comma separated).

**Comment by MindFlavor** [comment]
Good idea! On it!

**Comment by MindFlavor** [comment]
Done! Let me know if you encounter errors!
