### ISSUE TITLE
Prometeus can't scrape WG's metrics

### ISSUE THREAD

**Issue by Tarmik0s** [MindFlavor/prometheus_wireguard_exporter#78]
![image](https://user-images.githubusercontent.com/41224463/128106978-c3e1d3e5-7917-4d42-bc2c-2ad86d5a6a4e.png)

Hi,

I wanna ask if why I can't scrape the metrics from prometheus but I can curl it locally. Below is my prometheus scraping config

  - job_name: wg
    static_configs:
    - targets:
      - 127.0.0.1:9586
 
 
 Thanks!

**Comment by qdm12** [comment]
What network do you run the wireguard prometheus exporter? Are you running it on the host, as a container, something else?

Also how do you run Prometheus? On the host? As a container?
