### ISSUE TITLE
[feat request] ability to use env vars

### ISSUE THREAD

**Issue by jr0dd** [MindFlavor/prometheus_wireguard_exporter#79]
It would be nice to have the ability to set the cli flags with env vars

**Comment by MindFlavor** [comment]
Excellent idea!
Should be easy using Clap.

**Comment by MindFlavor** [comment]
dev branch: [issue/79/dev](https://github.com/MindFlavor/prometheus_wireguard_exporter/tree/issue/79/dev).

**Comment by jr0dd** [comment]
Awesome! I’ll have to test it out when I get some extra time.

**Comment by MindFlavor** [comment]
Done! 👍

**Comment by arisudesu** [comment]
Dockerfile wasn't updated accordingly. Please fix.
